import styles from './styles.module.css';
import ContactUs from '@components/ContactUs/index.jsx';

import Box from '@assets/images/box-2.png'

const ForCompanies = () => {
  return (
    <div className={'container ' + styles.container}>
      <div className={styles.wrapper}>
        <div className={styles.left}>
          <h1 style={{marginBottom: '20px'}}></h1>
          <p></p>
          <p>
            
          </p>
          <p>
            
          </p>
          <h2 style={{margin: '20px 0'}}>Interpretation and Definitions</h2>
          <h3 style={{marginBottom: '15px'}}>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <h3 style={{margin: '15px 0'}}>Definitions</h3>
          <p>
            For the purposes of this Privacy Policy:
          </p>
          <ul >
            <li style={{marginBottom: '5px'}}>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to EMGU LLC, Turon 1.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Cookies</strong> are small files that are placed on Your computer, mobile device, or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Country</strong> refers to: Uzbekistan.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li >
            <li style={{marginBottom: '5px'}}>
              <strong>Service</strong> refers to the Website.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Website</strong> refers to EMGU, accessible from www.emgu.uz.
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2 style={{margin: '20px 0'}}>Collecting and Using Your Personal Data</h2>
          <h3 style={{marginBottom: '10px'}}>Types of Data Collected</h3>
          <p style={{marginBottom: '5px'}}>
            <strong>Personal Data</strong>
            <br />
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul>
            <li style={{marginBottom: '5px'}}>First name and last name</li>
            <li style={{marginBottom: '5px'}}>Phone number</li>
            <li style={{marginBottom: '5px'}}>Address, State, Province, ZIP/Postal code, City</li>
            <li style={{marginBottom: '5px'}}>Company name and details about your company</li>
          </ul>

          <p>
            <strong>Usage Data</strong>
          </p>
          <h2>Usage Data</h2>
          <p></p>
          <h2>Tracking Technologies and Cookies</h2>
          <p></p>
          <ul >
            <li style={{marginBottom: '5px'}}>
              <strong>Cookies or Browser Cookies.</strong> means a unique account created for You to access our Service or parts of our Service.
              
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Web Beacons. </strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
              <p></p>
              <p></p>
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Necessary / Essential Cookies</strong> 
              <p></p>
              <p></p>
              <p></p>
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong> 
              <p></p>
              <p></p>
              <p></p>
            </li>
            <li style={{marginBottom: '5px'}}>
              <strong>Functionality Cookies</strong> 
              <p></p>
              <p></p>
              <p></p>
              <p></p>
            </li>            
          </ul>
          <h2>Use of Your Personal Data</h2>
          <p></p>
          <ul>
            <li>
              <strong>To provide and maintain our Service </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
            <li>
              <strong>Web Beacons. </strong> means
            </li>
          </ul>
          <h2>Retention of Your Personal Data</h2>
          <p></p>
          <h2>Transfer of Your Personal Data</h2>
          <p></p>
          <h2>Delete Your Personal Data</h2>
          <p></p>
          <h2>Disclosure of Your Personal Data</h2>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <h3>Business Transactions</h3>
          <p></p>
          <p></p>
          <p></p>
        </div>
        {/* <div className={styles.right}>
          <img src={Box} alt='box' width={332}/>
        </div> */}
      </div>
      <ContactUs />
    </div>
    
  );
};

export default ForCompanies;
